### ISSUE TITLE
Xcode 10 issue

### ISSUE THREAD

**Issue by rayrayrayyyym** [zaguiini/react-native-pure-jwt#1]
having an issue when building with the new xcode 10

![screen shot 2018-09-27 at 1 13 57 pm](https://user-images.githubusercontent.com/32053862/46124517-3dd34780-c257-11e8-89bb-772b3ef27f8c.png)

**Comment by waltershub** [comment]
did you find a solution

**Comment by rayrayrayyyym** [comment]
what i did is downgrade to xcode 9 hahaha

**Comment by waltershub** [comment]
I found a module called expo-jwt its pure js, time will tell if it’s performant enough for our needs but this lib has tremendous native setup

**Comment by aashryap** [comment]
No such module JWT on xcode 9. Works fine on android. I did all the required steps mentioned in the doc but still I am getting this error. Please help.

**Comment by aashryap** [comment]
I dont have any idea about xcode. Do i have to add something in bridging header file ?

**Comment by barclayd** [comment]
Thanks @waltershub for the excellent recommendation!

**Comment by zaguiini** [comment]
Hey Guys! So, I'm running a bit out of time right now, so I'm looking for people who can submit PRs and shit. Can someone here help me?

**Comment by zaguiini** [comment]
Hey, I've just released `v2`!
Please read the `README` and give me feedback. You don't need a bridge anymore.
