### ISSUE TITLE
Only see decode

### ISSUE THREAD

**Issue by jgarboza813** [zaguiini/react-native-pure-jwt#14]
When I try to use the sign function I am getting a "undefined is not a function" error. I inspected the contents of the jwt object and I only see the decode function available:

`
Object {
  "decode": [Function decode],
}
`

I am using the sample code and running on iOS through expo project. Any ideas?

**Comment by zaguiini** [comment]
I don't think using expo will work since you need to link the project. Can you confirm that for me with a full project instead of an expo one?
