### ISSUE TITLE
Secret should not be required for decode

### ISSUE THREAD

**Issue by MaffooBristol** [zaguiini/react-native-pure-jwt#15]
In the normal node-jsonwebtoken implementation, you can decode without providing a secret and it will still give you the payload. However this module requires the secret, which is something I don't particularly want to hard-code into my RN app.

Is there any way around this?

Thanks!
Matt

**Comment by zaguiini** [comment]
It currently doesn't allow it, but it can! PRs are open and I'd be glad if you fill one!

**Comment by MaffooBristol** [comment]
Okay I'll have a look into it next week, thanks :smile:

**Comment by sergchernata** [comment]
Was this ever implemented? I don't want to include the secret either.

**Comment by zaguiini** [comment]
Not so far. I have no time to do that by now. PRs are welcome!

**Comment by zaguiini** [comment]
As I can see, that functionality already exists! That's precisely what the `skipValidation` option does. You can pass an empty string as the secret and that should work. Please, try it!

**Comment by karpovSyned** [comment]
> As I can see, that functionality already exists! That's precisely what the `skipValidation` option does. You can pass an empty string as the secret and that should work. Please, try it!

No, it is not work. 
I have got an error got 
`jwt.decode(
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsIjoicGF5bG9hZCIsImlzcyI6Imx1aXNmZWxpcGV6QGxpdmUuY29tIiwiZXhwIjoxNTg4NjE4Nzg4fQ.fC5-Aw3AUtuWUKAwh9hWwRwadoAFAQOMroPnuxBvtgU', // the token
  '', // the secret is 'my-secret'
  {
    skipValidation: true, // to skip signature and exp verification
  },
)
  .then(console.log) // already an object. read below, exp key note
  .catch(console.error)`
