### ISSUE TITLE
In what formate should the secret be ? 

### ISSUE THREAD

**Issue by iyaseen** [zaguiini/react-native-pure-jwt#16]
In what formate the secrete param in decode method should be ?

**Comment by zaguiini** [comment]
According to the [typings](https://github.com/zaguiini/react-native-pure-jwt/blob/master/js/index.d.ts), the `secret` parameter is a string.

**Comment by iyaseen** [comment]
is it a base64 string or a big number string ? because I can see it's being decoded in RNPureJwt/RNPureJwtModule.java

**Comment by zaguiini** [comment]
It's a plain string.
