### ISSUE TITLE
INFO: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. It will be removed soon.

### ISSUE THREAD

**Issue by redefinered** [zaguiini/react-native-pure-jwt#17]
Does anyone still update this package? Android shows this Gradle sync issue

**Comment by zaguiini** [comment]
I'm not having much time to do so. You can do it if you feel like it, as I'm looking for maintainers!

But your issue description doesn't help since it doesn't say much. Can you please post a screenshot of the Gradle sync issue you're having and can you propose a fix or something?

**Comment by redefinered** [comment]
Actually, the problem I'm having is my project is not being built in App Center :D

```
com.zaguiini.RNPureJwt.RNPureJwtModule.toBase64 RNPureJwtModule.java:44
com.zaguiini.RNPureJwt.RNPureJwtModule.decode RNPureJwtModule.java:99
java.lang.reflect.Method.invoke Method.java
com.facebook.react.bridge.JavaMethodWrapper.invoke JavaMethodWrapper.java:372
com.facebook.react.bridge.JavaModuleWrapper.invoke JavaModuleWrapper.java:158
com.facebook.react.bridge.queue.NativeRunnable.run NativeRunnable.java
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage MessageQueueThreadHandler.java:29
android.os.Looper.loop Looper.java:214
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run MessageQueueThreadImpl.java:232
java.lang.Thread.run Thread.java:764
```

Is this an issue with linking? I just saw the `compile` to `implementation` stuff in Android Studio, I'm not actually sure if that is causing the problem with building in App Center

**Comment by zaguiini** [comment]
Can you please show exactly what is wrong with the lib itself? If you can't do it, I'll have to close this issue and you'll have to create an issue on StackOverflow as it's better suited for this case of problem.

The problem you're reporting doesn't sound like a bug in the lib. Have you tried unlinking and linking again? Have you tried to build in Android Studio? Have you tried linking with the `implementation` keyword instead of `compile`?

**Comment by redefinered** [comment]
What I remember is I followed the instructions in the installation section in repo overview and my app failed to build. I just unlinked the package and my issue is solved.

**Comment by jrobber** [comment]
@zaguiini If you make these two changes to build.grade it fixes this error, and the `Android resource linking faile
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.` error

Change 1 - minimum sdk version (I believe you can go as low as 24, but 28 is the accepted standard minimum right now) (link: https://stackoverflow.com/questions/49331411/errorresource-androidstyle-textappearance-material-widget-button-borderless-co) :
```
android {
    compileSdkVersion 23 -> 28
    ....
```

Change 2: change compile to implementation
```
dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'io.jsonwebtoken:jjwt:0.9.0'
}
```
```
dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation 'io.jsonwebtoken:jjwt:0.9.0'
}
```

**Comment by zaguiini** [comment]
Hey there @jrobber, thanks for the suggestion! Could you please create a PR with those changes? Thanks!
