### ISSUE TITLE
Error on Android Device: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference

### ISSUE THREAD

**Issue by redefinered** [zaguiini/react-native-pure-jwt#18]
I followed the installation instructions in overview which are:

```
yarn add react-native-pure-jwt
```

and

```
react-native link eact-native-pure-jwt
```

I also checked for the ff files:

1. MainApplication.java
2. android/app/build.gradle
3. android/settings.gradle

if the necessary changes has been made for android to be linked properly and I still get this error when running on a physical Android Device

Here is the complete thread

```
com.zaguiini.RNPureJwt.RNPureJwtModule.toBase64 RNPureJwtModule.java:44
com.zaguiini.RNPureJwt.RNPureJwtModule.decode RNPureJwtModule.java:99
java.lang.reflect.Method.invoke Method.java
com.facebook.react.bridge.JavaMethodWrapper.invoke JavaMethodWrapper.java:372
com.facebook.react.bridge.JavaModuleWrapper.invoke JavaModuleWrapper.java:158
com.facebook.react.bridge.queue.NativeRunnable.run NativeRunnable.java
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage MessageQueueThreadHandler.java:29
android.os.Looper.loop Looper.java:214
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run MessageQueueThreadImpl.java:232
java.lang.Thread.run Thread.java:764
```

<img width="878" alt="Screen Shot 2019-10-23 at 17 40 42" src="https://user-images.githubusercontent.com/5173630/67379992-457d3100-f5bc-11e9-849c-fc4ca6d7ae4a.png">

Packages versions:
react-native: 0.60.5
react-native-pure-jwt: 2.1.1

**Comment by redefinered** [comment]
I think that the `toBase64` method is generating the issue in `RNPureJwtModule.java:44`

**Comment by zaguiini** [comment]
If this is null you're probably not passing the secret.
