### ISSUE TITLE
Looks like Android is not working on release mode. I can not see any error logs as it is already installed as APK on physical android device

### ISSUE THREAD

**Issue by reddeguzman** [zaguiini/react-native-pure-jwt#19]
I don't know how to reproduce the error because there is no error log when installed as APK

**Comment by zaguiini** [comment]
So uninstall it and try building again and installing and you should see the error

**Comment by reddeguzman** [comment]
You mean reinstall?

**Comment by reddeguzman** [comment]
It is working on debug mode. When the Android device is connected to my computer. When I run `react-native run-android` while a device is connected to my computer, it works. But when I install the app from an APK, it doesn't

**Comment by zaguiini** [comment]
Yes, try reinstalling. Cleaning the project, building and installing on Release mode. Check `adb logcat` for errors.

**Comment by RodrigoSarmento** [comment]
I'm having the same issue, looks like when I use Signin with a empty secret it crashes on Android and it works on IOS
