### ISSUE TITLE
Cannot read property 'sign' of undefined

### ISSUE THREAD

**Issue by ashwinirajput** [zaguiini/react-native-pure-jwt#2]
Cannot read property 'sign' of undefined
react-native:57.0

**Comment by colin-kudos** [comment]
Same issue

**Comment by e55o** [comment]
i also have the same issue, with `react-native: 0.58.4`

**Comment by zaguiini** [comment]
Hey Guys! So, I'm running a bit out of time right now, so I'm looking for people who can submit PRs and shit. Can someone here help me?

**Comment by zaguiini** [comment]
Hey, I've just released `v2`!
Please read the `README` and give me feedback.

**Comment by sleekLancelot** [comment]
Please can this issue be re-opened?
I am getting this error also on, using "react-native-pure-jwt": "^3.0.2" and "react-native": "0.71.8"
