### ISSUE TITLE
Not working with versions >=0.60

### ISSUE THREAD

**Issue by erhan355** [zaguiini/react-native-pure-jwt#20]
After installing package with npm ,project didn't compile and got the error below.As you now ,React Native CLI uses autolinking.I also  tried to unlink and proceed with manual installing as you showed at installation section.But nothing to avail.
Enviroment: Vs Code
Versions: 
"react-native": "0.61.1"
"react-native-pure-jwt": "2.1.1"

error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-pure-jwt (to unlink run: "react-native unlink react-native-pure-jwt")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.

**Comment by zaguiini** [comment]
Yeah, the library is pretty much outdated regarding newer versions of `react-native`. I'd love to see a PR addressing this issue as I, unfortunately, don't have much time to work on it.

**Comment by zaguiini** [comment]
Fixed in `v2.2.0`.
