### ISSUE TITLE
iOS install via Cocoapods, branches do not exist

### ISSUE THREAD

**Issue by rezaarifian** [zaguiini/react-native-pure-jwt#25]
run `pod install` get error result. I am using `react-native-pure-jwt": "2.2.1"`

<img width="495" alt="Screen Shot 2020-11-18 at 17 17 51" src="https://user-images.githubusercontent.com/16816082/99517484-02111400-29c2-11eb-85cd-2c4f01f658ab.png">

**Comment by zaguiini** [comment]
Sorry. Can you try it again, @rezaarifian?

**Comment by akshaypunchh** [comment]
@zaguiini 
<img width="579" alt="Screenshot 2021-05-05 at 2 48 57 PM" src="https://user-images.githubusercontent.com/8625316/117120573-1e0e4380-adb1-11eb-8217-b0a07ebe8b50.png">

**Comment by akshaypunchh** [comment]
Hello @rezaarifian , Do you know any alternate library which can be used at the place of react-native-pure-jwt.
