### ISSUE TITLE
#import "React/RCTBridgeModule.h" not found

### ISSUE THREAD

**Issue by Malikkhoja** [zaguiini/react-native-pure-jwt#3]
Hi @zaguiini ,

I installed react-native-pure-jwt in my react native project. Everything seems to be working fine on android. However, on IOS, I get 2 error.

1. #import "React/RCTBridgeModule.h" not found
2. Failed to emit precompiled header '/Users/apple/Library/Developer/Xcode/DerivedData/

I have already tried many solutions. But they don't seem to work. I have unchecked parallelized build and my react is on top in Target Section. As instructed in library documentation, I have added the JWT swift file in libraries.

React Native - 0.58.5
react-native-pure-jwt- v1.6.0

Still, it's not working. Any help would be great.

Thanks in advance

**Comment by zaguiini** [comment]
Hey Guys! So, I'm running a bit out of time right now, so I'm looking for people who can submit PRs and shit. Can someone here help me?

**Comment by Senocico** [comment]
The same issue...

**Comment by zaguiini** [comment]
> Hey Guys! So, I'm running a bit out of time right now, so I'm looking for people who can submit PRs and shit. Can someone here help me?

The same issue...

**Comment by zaguiini** [comment]
Hey. I've just released `v2`. Please read the README and give me a feedback. You don't need a bridge anymore.
