### ISSUE TITLE
Read payload without secret key

### ISSUE THREAD

**Issue by ErtugrulBEKTIK** [zaguiini/react-native-pure-jwt#30]
In JWT we can read payload without secret key. I try to use skipValidation option as true and give secret as null. Then it is still giving an [Error: Decoding failed] error. 

For quick solution I pick the payload part of the token and decode it with base-64

```javascript
import {decode} from 'base-64';

const payload = JSON.parse(decode(token.split('.')[1]));
```

**Note:** I use base-64 npm package to decode, btoa is not working correctly in React Native.

**Comment by zaguiini** [comment]
As stated in the README, you can call `.decode` with

```js
{ skipValidation: true }
```

As the 3rd argument and you'll achieve that.
