### ISSUE TITLE
Error 'npm i react-native-pure-jwt'

### ISSUE THREAD

**Issue by ivaldo** [zaguiini/react-native-pure-jwt#35]
I try install the npm dependency but occurs an error.

** Command
> npm i react-native-pure-jwt

** Error reported
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: identidadefuncionaltjdft@0.0.1
npm ERR! Found: react-native@0.66.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.66.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-pure-jwt@3.0.0
npm ERR! node_modules/react-native-pure-jwt
npm ERR!   react-native-pure-jwt@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution

**My environment
 - OS: Windows 10
 - My package.json
 "dependencies": {
    "@react-native-async-storage/async-storage": "1.15.14",
    "@react-native-community/geolocation": "2.0.2",
    "@react-native-community/masked-view": "0.1.11",
    "@react-navigation/bottom-tabs": "6.0.9",
    "@react-navigation/native": "6.0.6",
    "@react-navigation/stack": "6.0.11",
    "axios": "0.24.0",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-base64": "^0.2.1",
    "react-native-gesture-handler": "2.1.0",
    "react-native-global-font": "1.0.3",
    "react-native-permissions": "3.2.0",
    "react-native-reanimated": "2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "3.10.1",
    "react-native-svg": "12.1.1",
    "react-native-svg-transformer": "0.20.0",
    "react-native-swiper": "1.6.0",
    "styled-components": "5.3.3"
  },

**Comment by jan-bogaerts** [comment]
try to install with yarn, that worked with me.

**Comment by dirkpostma** [comment]
I got same error when using node with arm64 architecture. With x64 it error was resolved.
You can check your node architecture by running command `node -p process.arch`
