### ISSUE TITLE
Create new release and changelog

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [zaguiini/react-native-pure-jwt#36]
It would be great if one can just go to Release section and see the API changes.

For example, from 2.2.2 to 3.0.0, named import can now be used.

**Comment by zaguiini** [comment]
Sorry for that, life's been crazy and I have little to no time to maintain the project. I grew up a lot as an engineer in the last 3 years so a lot of things on how I approach OSS projects changed, including maintenance and the releases section. I totally agree with you and in the future I'll try and spent more time with the changelog for example. Thanks for the message!
