### ISSUE TITLE
Xcode 10.2 prompt: Swift upgrade from 3.x to 4 is required

### ISSUE THREAD

**Issue by unmec** [zaguiini/react-native-pure-jwt#4]
Please see screenshot
<img width="466" alt="swift" src="https://user-images.githubusercontent.com/15188710/55221232-f8aec300-5243-11e9-888e-f30c77bd3a87.png">

**Comment by wiyantotan** [comment]
Same here

**Comment by zaguiini** [comment]
Hey Guys! So, I'm running a bit out of time right now, so I'm looking for people who can submit PRs and shit. Can someone here help me?

**Comment by zaguiini** [comment]
Hey. I've just released `v2`. Please read the README and give me a feedback.
