### ISSUE TITLE
Set compileSdkVersion to 30 or above

### ISSUE THREAD

**Issue by vaandhare** [zaguiini/react-native-pure-jwt#45]
"react": "^18.2.0",
"react-native": "^0.72.0",
"react-native-pure-jwt": "^3.0.1",

Error:
Execution failed for task ':tasks'.
> Could not create task ':react-native-pure-jwt:compileDebugJavaWithJavac'. > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above *

**Comment by DevopsDood** [comment]
Same issue

**Comment by OPADA-Eng** [comment]
Hi 
I used to solve this issue as a workaround by changing the **compileSdkVersion** version in the plugin files to **33**

**Comment by vaandhare** [comment]
@OPADA-Eng,
I'm also doing this as temporary workaround, but need permanent solution.

**Comment by dcc82** [comment]
I've resolved the issue by making the changes below to the "build.gradle" file.

After the line: apply plugin: 'com.android.library', add:
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

Change:
    compileSdkVersion 28
    buildToolsVersion "23.0.1"

To:
    compileSdkVersion safeExtGet('compileSdkVersion', 28)
    buildToolsVersion safeExtGet('buildToolsVersion', '23.0.1')

**Comment by CostasCF** [comment]
I have the same issue after upgrading to Expo SDK 49..

**Comment by zaguiini** [comment]
Fixed
