### ISSUE TITLE
/react-native-pure-jwt/ios/RNJwtIos/RNJwtIos-Bridging-Header.h:5:9: error: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by idoor88** [zaguiini/react-native-pure-jwt#5]
I followed your instruction, installed and configured the library in XCode, but when I build in xcode, I got the link error:

/react-native-pure-jwt/ios/RNJwtIos/RNJwtIos-Bridging-Header.h:5:9: error: 'React/RCTBridgeModule.h' file not found

**Comment by zaguiini** [comment]
Hey. Thanks for opening this issue. I'm actually rebuilding the lib from scratch. You can follow up on the `v2` branch. It's a WIP, will release in the next few days.

**Comment by zaguiini** [comment]
Hey. I've just released `v2`. Please read the README and give me a feedback.
