### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by suthat** [zaguiini/react-native-pure-jwt#6]
info .../node_modules/react-native-pure-jwt/ios/RNPureJwt.m:3:9: fatal error
info
info : 'JWT.h' file not found
info #import "JWT.h"
        ^~~~~~~
info 1 error generated.

Build on iOS 12
Xcode 10.2.1
RN 0.59.5

**Comment by SaraChicaD** [comment]
Also just got this. Any fixes?

**Comment by SaraChicaD** [comment]
@zaguiini i've tried `1.5.x`, `1.6.0` and `2.0.1` of this project, tried opening it in XCode, tried to install via Pods (though the instructions weren't very clear so I may not have done that correctly) and I either get that `#import JWT` or `#import "JWT.h"` cannot be found. Do you have any ideas? I'm kind of desperate, thanks in advance!

**Comment by zaguiini** [comment]
Have you added the dependency on the podfile and then run pod install?

**Comment by zaguiini** [comment]
@sarachicad you don’t need to manually link the project, only install it via pods

**Comment by SaraChicaD** [comment]
Thank you @zaguiini as I mentioned, I wasn't sure how to do that given that it's not in the docs, just add this to my Podfile? Thank you so much!!!

`pod 'RNPureJwt', :podspec => '../node_modules/react-native/third-party-podspecs/RNPureJwt.podspec'`

**Comment by zaguiini** [comment]
> Thank you @zaguiini as I mentioned, I wasn't sure how to do that given that it's not in the docs, just add this to my Podfile? Thank you so much!!!
> 
> `pod 'RNPureJwt', :podspec => '../node_modules/react-native/third-party-podspecs/RNPureJwt.podspec'`

Quite close! That's the line:

`pod 'RNPureJwt', :podspec => '../node_modules/react-native-pure-jwt/RNPureJwt.podspec'`

**Comment by suthat** [comment]
Thank you guys.

**Comment by SaraChicaD** [comment]
@suthat could you please share your podfile / library version with me? i'm still having trouble, though the errors from this new approach are MUCH more promising lol. thank you!!

**Comment by zaguiini** [comment]
What errors are you having, @sarachicad?

**Comment by SaraChicaD** [comment]
Thank you @zaguiini I appreciate your interest & help -- I'll do a PR with documentation updates when I can figure this out to pay you back :)

This is my Podfile:

```
target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # Third party deps podspec link
  pod 'RNPureJwt', :podspec => '../node_modules/react-native-pure-jwt/RNPureJwt.podspec'

  # Pods for labl

end
```

This is my error:

```
### Error

Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/sarainescalderon/Documents/docs/proj/node_modules/react-native-pure-jwt/RNPureJwt.podspec
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `initialize'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:825:in `fetch_external_source'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:804:in `block (2 levels) in fetch_external_sources'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:803:in `each'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:803:in `block in fetch_external_sources'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:802:in `fetch_external_sources'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:266:in `analyze'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:136:in `install!'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/command/install.rb:48:in `run'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/command.rb:52:in `run'
/Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/bin/pod:55:in `<top (required)>'
/Users/sarainescalderon/.rbenv/versions/2.4.1/bin/pod:22:in `load'
/Users/sarainescalderon/.rbenv/versions/2.4.1/bin/pod:22:in `<main>'
```

**Comment by zaguiini** [comment]
> Thank you @zaguiini I appreciate your interest & help -- I'll do a PR with documentation updates when I can figure this out to pay you back :)
> 
> This is my Podfile:
> 
> ```
> target 'app' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   use_frameworks!
>   # Third party deps podspec link
>   pod 'RNPureJwt', :podspec => '../node_modules/react-native-pure-jwt/RNPureJwt.podspec'
> 
>   # Pods for labl
> 
> end
> ```
> 
> This is my error:
> 
> ```
> ### Error
> 
> Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/sarainescalderon/Documents/docs/proj/node_modules/react-native-pure-jwt/RNPureJwt.podspec
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `initialize'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:825:in `fetch_external_source'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:804:in `block (2 levels) in fetch_external_sources'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:803:in `each'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:803:in `block in fetch_external_sources'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:64:in `section'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:802:in `fetch_external_sources'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:266:in `analyze'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/user_interface.rb:64:in `section'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/installer.rb:136:in `install!'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/command/install.rb:48:in `run'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/lib/cocoapods/command.rb:52:in `run'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.2/bin/pod:55:in `<top (required)>'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/bin/pod:22:in `load'
> /Users/sarainescalderon/.rbenv/versions/2.4.1/bin/pod:22:in `<main>'
> ```

Try doing `pod setup` and then running `pod install`.

**Comment by SaraChicaD** [comment]
Ok @zaguiini I did all that, but the Podfile wasn't showing up in the `node_module` folder so I cloned it from _this_ repo, dropped it into the `node_module` folder and it's installing! But now I get this error: 

```
Analyzing dependencies
Fetching podspec for `RNPureJwt` from `../node_modules/react-native-pure-jwt/RNPureJwt.podspec`
Downloading dependencies
Installing Base64 (1.1.2)
Installing JWT (3.0.0-beta.11)
Installing RNPureJwt (2.1.0)

[!] Error installing RNPureJwt
[!] /usr/bin/git clone git+https://github.com/zaguiini/react-native-pure-jwt.git /var/folders/k7/0jw3kdl14jjfc6j55sh0lxhm0000gn/T/d20190516-10954-14qnkes --template= --single-branch --depth 1 --branch 2.1.0

Cloning into '/var/folders/k7/0jw3kdl14jjfc6j55sh0lxhm0000gn/T/d20190516-10954-14qnkes'...
warning: Could not find remote branch 2.1.0 to clone.
fatal: Remote branch 2.1.0 not found in upstream origin
```

**Comment by zaguiini** [comment]
But the Podfile isn’t supposed to be in the `node_modules` folder? It is in the `ios` folder. Can you show me your `Podfile`?

**Comment by SaraChicaD** [comment]
Sorry, I mean the `podspec` file -- it didn't show up in the `node_modules`, so I had to add it manually. Then when I ran `install` it gave me the previous [error](https://github.com/zaguiini/react-native-pure-jwt/issues/6#issuecomment-493303716). 

Podfile:

```
  target 'labl' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for labl
  pod 'RNPureJwt', :podspec => '../node_modules/react-native-pure-jwt/RNPureJwt.podspec'
end

```

> But the Podfile isn’t supposed to be in the `node_modules` folder? It is in the `ios` folder. Can you show me your `Podfile`?

**Comment by zaguiini** [comment]
> Sorry, I mean the `podspec` file -- it didn't show up in the `node_modules`, so I had to add it manually. Then when I ran `install` it gave me the previous [error](https://github.com/zaguiini/react-native-pure-jwt/issues/6#issuecomment-493303716).
> 
> Podfile:
> 
> ```
>   target 'labl' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for labl
>   pod 'RNPureJwt', :podspec => '../node_modules/react-native-pure-jwt/RNPureJwt.podspec'
> end
> ```
> 
> > But the Podfile isn’t supposed to be in the `node_modules` folder? It is in the `ios` folder. Can you show me your `Podfile`?

Kinda strange it doesn't shows there. Can you please remove `node_modules` folder, retry `yarn add react-native-pure-jwt` and then `pod install`?

**Comment by daxaxelrod** [comment]
HOLY MOLY. That was 3 hours of my life I'll never get back.
Go back to the same dir that your package.json is in.

`react-native unlink react-native-pure-jwt`
`cd ios/`
`rm -rf Pods/`
`pods install`
`cd .. && react-native run-ios`

**Comment by Hamashassan** [comment]
In Pod file of your project

**Change this line** 

`pod 'RNPureJwt', :path => '../node_modules/react-native-pure-jwt'
`

**to this**

`pod 'react-native-pure-jwt', :path => '../node_modules/react-native-pure-jwt/react-native-pure-jwt.podspec'

basically, the path is not right.
`
