### ISSUE TITLE
iOS install via Cocoapods, branches do not exist

### ISSUE THREAD

**Issue by ochrstn** [zaguiini/react-native-pure-jwt#8]
I can't install the library using Cocoapods because it tries to access git branches that don't exist.

```
[!] Error installing RNPureJwt
[!] /usr/bin/git clone https://github.com/zaguiini/react-native-pure-jwt.git /var/folders/v0/n5lq_ggx5fg4n2lw3xlkqtn00000gn/T/d20190521-40030-nkgbd0 --template= --single-branch --depth 1 --branch 2.0.1

Cloning into '/var/folders/v0/n5lq_ggx5fg4n2lw3xlkqtn00000gn/T/d20190521-40030-nkgbd0'...
warning: Could not find remote branch 2.0.1 to clone.
fatal: Remote branch 2.0.1 not found in upstream origin
```

**Comment by zaguiini** [comment]
Could you please retry, @ochrstn?

Also, have you installed via NPM?

**Comment by ReactiveSainz** [comment]
> Could you please retry, @ochrstn?
> 
> Also, have you installed via NPM? Because you need to install (using yarn or npm) before trying to `pod install`

I also have the same problem

**Comment by zaguiini** [comment]
> > Could you please retry, @ochrstn?
> > Also, have you installed via NPM? Because you need to install (using yarn or npm) before trying to `pod install`
> 
> I also have the same problem

That's strange because the branch exists. Can you run `pod update` and try again, please?

**Comment by ReactiveSainz** [comment]
same error after doing the pod update 
![image](https://user-images.githubusercontent.com/25291552/60195564-eb808080-9800-11e9-9375-6ffd30008328.png)

**Comment by zaguiini** [comment]
Ohh, I created with the wrong name xD Sorry, will update that.

**Comment by Rushi271193** [comment]
Error installing RNPureJwt
[!] /usr/local/bin/git clone git+https://github.com/zaguiini/react-native-pure-jwt.git /var/folders/0w/rd8_92y50fn07t9qxy5r_txw0000gp/T/d20190719-50561-15welbu --template= --single-branch --depth 1 --branch 2.1.0

Cloning into '/var/folders/0w/rd8_92y50fn07t9qxy5r_txw0000gp/T/d20190719-50561-15welbu'...
fatal: unable to find remote helper for 'git+https'

I am getting the above error

**Comment by daxaxelrod** [comment]
@Rushi271193 You can fix that by going into the package.json file of your copy of react-native-pure-jwt in node_modules. Just change the repository.url from git+https://blahblah to just https://blahblah

**Comment by zaguiini** [comment]
@daxaxelrod great! Mind filing a PR?

**Comment by daxaxelrod** [comment]
Of course! Will do later tonight

**Comment by daxaxelrod** [comment]
Actually just checked. The repo seems up to date, I think the npm package just needs to be updated :D

**Comment by zaguiini** [comment]
The npm package has the correct content as well... Not sure what's happening.

![Uploading Screen Shot 2019-07-20 at 21.04.53.png…]()

**Comment by zaguiini** [comment]
The npm package looks ok... Not sure what's happening, can you provide evidence @daxaxelrod ?

**Comment by daxaxelrod** [comment]
Sure np
I just created a fresh project called jwttest with the following
react-native-cli: 2.0.1
react-native: 0.60.4

when installed this package, npm put this in my package.json 
"react-native-pure-jwt": "^2.1.0"

I added the podspec in the readme to my podfile and did pod install. Got the same error as the other guys.
<img width="836" alt="Screen Shot 2019-07-20 at 11 25 52 PM" src="https://user-images.githubusercontent.com/10982992/61586582-d966d900-ab45-11e9-9951-d9aa7a0392a6.png">

<img width="1680" alt="Screen Shot 2019-07-20 at 11 30 39 PM" src="https://user-images.githubusercontent.com/10982992/61586604-98bb8f80-ab46-11e9-9752-6387686855b1.png">

**Comment by daxaxelrod** [comment]
I also just checked your latest release labeled library rewrite and it looked good! So strange!

**Comment by zaguiini** [comment]
I think I get it now. We’ll need to make the repo literal instead of referencing the repo url on the package json. I’ll do that later and publish a new version

**Comment by zaguiini** [comment]
Just published a new version. Could you guys please test?
